#+TITLE: 2016 Troop 675 Robotics Merit Badge Class Competition:  Robo Relay
#+AUTHOR: Maurice Ling
#+DATE: 2016-08-29
* Competition Date, Location, and Schedule
  - Date:  Monday, August 29, 2016
  - Time:  6:00-8:30pm
  - Location:  Light of Christ Church Fellowship Hall
  - Schedule:
    - 6:00 pm Setup
    - 6:30 pm Design Review with Judges
    - 7:00 pm Competition Start
    - 8:00 pm Competition results
* Summary
  The competition will be a relay race between two teams, completing
  7 segments as specified in the /Relay Segments/ section.
  After completing the objectives of each segment, each robot shall 
  autonomously hand off control to the next robot, then come to a stop.
  
  Points will be awarded based the engineering notebooks of each scout and
  finishing each segment of the relay race in the shortest time.  Specific
  rules are listed in the /Rules/ section.

* Competition Specifications  
** Hardware/Software
   1. The robot shall utilize the Edison robot platform
   2. The robots shall be programmed by the participant for each segment
   3. The design documentation shall be in the
      participant's engineering notebook for judge's review.
** Scoring  
   1. Design documentation - Up to +30 points per scout awarded as follows;
      1) Programming logic (+5)
         - Clearly describe the flow of the program.
      2) Physical design (+5)
         - Describe parts of the robot and how they function
      3) Electrical design (+5)  
         - Sensor Inputs - Describe the sensors and how they are are used.
         - Power - Describe what provides power to the robot
      4) Testing & Results (+5)
         - What tests did you perform and how did your robot perform
      5) Neatness/organization (+5)
         - Clearly labeled sections, tables, diagrams, pictures.
      6) Elegant and innovative design (+5)
         - These points are awarded for designs show
           creativity and innovation in performing the designated
           tasks.
   2. Completion of each segment +20 points
   3. Best time for each segment +10 points
   4. Point Penalties
      1) Physical intervention (-5)
      2) Time limit exceeded for segment (-5)
      3) Barrier/boundary movement (-5)
      4) Improper hand-off (-5)
** Relay
   1. Timing starts when the first robot program starts.
   2. Each segment will be timed.
   3. Time to complete each segment shall not exceed 5 minutes.
   4. Robots shall stay within the boundaries of the course.
   5. Robots shall not move boundaries or obstacles in its way.
   6. The participant shall not touch the robot after the initial placement.
   7. All robots for the team shall be in place prior to starting the relay.
   8. Segment shall be considered complete when hand-off is complete, or
      in the case of segment 7, the finish line is crossed.
   9. Segments 3 and 5, the participant may optionally place one stationary 
      object on the course to assist in the task.
*** Hand-Offs
    1. Hand-offs shall be performed between segments.
    2. Hand-off between robots shall be done autonomously.  No human interaction
       or control is allowed.
    3. The receiving robot shall beep 3 times to indicate a successful hand-off.
    4. The receiving robot shall send data back to the sender to acknowledge receipt.
    5. The sending robot shall receive the acknowledgement (ack) and blink 3 times
       to indicate receipt.
    6. The hand-off is considered once the ack sequence is complete.
    7. The sending robot shall remain stationary after the hand-off.
    8. Autonomous hand-off will be facilitated by a approximately 30 inch long 
       1.5cm wide black line.  The receiving robot will be positioned and the 
       end of this line.
*** Segment 1 - Light Navigation
**** Description
     The robot will autonomously heading toward the light while 
     avoid the obstacles that are in the way.  When the robot detects
     the hand-off line, it will navigate the line until it reaches the 
     next robot for the automated hand-off.
**** Keys to Success
     Relative lighting levels between the left and right light sensors 
     determine the direction the robot should 
     head in.  Obstacle sensor reading and light level detection both need to
     be considered when determining what direction to go in.  Key test
     case is what to do if there is an object between the light the robot.
     The line sensor detecting a non-reflecting surface shall trigger the 
     automated hand-off sequence.
*** Segment 2 - Line Maze
**** Description
     The robot will autonomously navigate a line maze, detecting items in its path.
     The item may be a road block, which means it is a dead end, or it could
     be the next robot!  
**** Keys to Success
     Combine the line following algorithm with an event which detects obstacles.
     When an obstacle is detected, determine if it is a robot for hand-off
     or an obstacle.  Send the hand-off code and wait for an ack.
     If there is no ack, turn around and continue navigating the 
     line maze until you get an ack.
*** Segment 3 - Ping Pong Collection
**** Description
     After the robot acknowledges the hand-off from the Segment 2 robot,
     the participant shall control the robot with the IR controller to place
     3 ping pong balls into a tray with a 1 inch high edge.  After succeeding 
     at this task, the the robot shall switch into autonomous mode to hand off 
     to the next robot.
**** Keys to Success
     Design robot to be able to collect and lift ping pong balls and transport
     them to the tray. Program one button to switch the robot into autonomous
     hand-off mode.
*** Segment 4 - Speedway
**** Description    
     The participant shall control the robot with an IR controller to 
     speed through a race course 3 laps.  After the third lap, the
     the robot shall switch into autonomous mode for the hand off to the next robot.
**** Keys to Success
     Design for speed and agility.  Consider how to make
     your robot faster (gears, wheels, etc) and easier to turn.
     Program one button to switch the robot into autonomous hand-off mode.
*** Segment 5 - Push the Cans
**** Description
     The participant shall control the robot with an IR controller to
     push three 6 oz cans into a designated target area.  
     After completing the task, the robot shall switch into autonomous mode
     to hand off to the next robot.
**** Keys to Success
     Mechanical design to be able to drive and push a can around.
     Consider that the can could be on its side as well.
     Program one button to switch the robot into autonomous hand-off mode.
*** Segment 6 - Clap controlled Driving
**** Description
     The participant shall control the robot to navigate through a course
     by using clapping as the primary method of control.  When the robot
     detects the hand-off line, it shall autonomously navigate to hand off to
     the next robot.
**** Keys to Success
     Ability to encode claps into commands.  Count the number of claps in
     a set amount of time, then convert that into a command to the motors.
     Remember that if the motors are on, the sound sensor will detect that sound!
     Make sure the motors are off when processing the claps.
*** Segment 7 - Search and rescue
**** Description
     The Robot shall autonmously search within an area for a target spot.
     Once it discovers the spot, it shall play a musical tune and then 
     head toward the light located at the finish line, being careful to avoid
     any obstacles on its way.  Relay is complete when the robot passes
     the finish line.
**** Keys to Success
     Algorithm to navigate a pattern within an enclosed area.  Be sure to use the 
     obstacle sensor inputs to detect the boundaries and obstacles.  
     Have an event to trigger if line tracker
     detects a non-reflecting surface which marks the target. 
     Once the target is detected, play a musical tune and switch into 
     light controlled driving with obstacle detection.  See segment 1's
     Keys to Success.
     
