#+TITLE: Robotics Merit Badge Class Reference
#+AUTHOR: Maurice Ling
#+DATE: 2016-07-03

* Introduction
  This document contains useful information for the 
  2016 Troop 675 Irvine Robotics Merit Badge class.

  Copyright © 2016 Maurice Ling

* Items to bring for each Session
   - Laptop/computer/tablet with EdWare access. (see Section: [[Computer Requirements]])
   - Power adapter/cable.
   - Pen/pencil for taking notes
   - Robotics Notebook and Ediston Robot Kit (distributed in first class)
   - Charged AAA batteries (bring 4 alkaline AAA batteries for first class)
   - [[http://www.apu.edu/library/educationalprograms/stemnova/downloads/prerequisites/Robotics.pdf][Workbook]] (Print out for first class)
   - Blue Card signed by Scoutmaster
   - EdCom programming cable (included with Edison Robot)

* Computer Requirements

  You need a computer or tablet (Mac, Windows PC, or Linux) with audio output
  capability and standard 1/8" audio jack.  Wifi is highly recommended.

** EdWare Programming software

   The class will be taught using the on-line version of Edware.  The on-line 
   version allows you to share programs with each other, which is useful
   if you need help with debugging your program.

   EdWare is available [[http://edwareapp.com/?_ga%3D1.185565985.982237356.1463279107#][on-line]] for free via web browser.  Create an account via 
   *Menu->Login*

   For off-line access, versions for Windows, Mac, Linux, Android, iOS
   are also freely available at
   https://meetedison.com/robot-programming-software/.  You may try
   these out for a back up to the online version, but the online version is preferred 
   and has more features.  If you want to program without a network connection,
   install one of these alternatives.

* Other Items You Will Need
  - Blue Card with the Scoutmaster’s signature.
  - AAA NiMH battery charger (the kit you will receive will include
    AAA NiMH batteries).
  - A small work area at home you can use to work on your robot.
  - Sony compatible or universal IR remote
  - Legos.  I will have a limited number of random special connector Lego
    parts available, but you will be expected to provide the
    majority of Lego parts for your robot.  If you'd like to
    purchase a set, the "Compact Tracked Loader" (Lego set 42032)
    has useful parts and is used as an example in some of the
    documentation from EdWare. (Useful, but not required)
  - You may want to purchase and read the [[http://www.scoutstuff.org/robotics-merit-badge-pamphlet.html#.V3oLh3rivRZ][Robotics Merit Badge pamphlet]] or the [[http://www.scoutstuff.org/interactive-digital-robotics-merit-badge-pamphlet.html#.V3oL2XrivRY][Interactive Digital version]] of
    the pamphlet
* References
  - [[https://meetedison.com/content/EdBooks/EdBook1-Your-EdVenture-into-Robotics-You-re-a-Controller.pdf][EdBook 1 - You're a Controller]]
  - [[https://meetedison.com/content/EdBooks/EdBook2-Your-EdVenture-into-Robotics-You-re-a-Programmer.pdf][EdBook 2 - You're a Programmer]]
  - [[https://meetedison.com/content/EdBooks/EdBook3-Your-EdVenture-into-Robotics-You-re-a-Builder.pdf][EdBook 3 - You're a Builder]]

